; concise-mid-tag
comid.language = 0
comid.tag-metadata = 1
comid.module-metadata = 2
comid.entity = 3
comid.linked-tags = 4
comid.claims = 5

; tag-metadata-map
comid.tag-id = 0
comid.tag-version = 1

; module-metadata-map
comid.element-name = 0
comid.module-version = 1

; linked-tag-map
comid.linked-tag-id = 0
comid.tag-rel = 1

; $tag-rel-choice values
;
; The current module has additional module(s) identified by
; the linked tag(s). The union of all modules describes an
; acceptable device.
comid.includes = 0
; The current module has additional module(s) identified by
; the linked tag(s) that describe alternative acceptable
; modules. At least one of the alternatives is included to
; describe an acceptable device.
comid.or-includes = 1
; The current module has additional claims that augment the
; claim set of the target module. The current tag module
; information must match the target module for the claims to
; be combined under the target.
comid.supplements = 2
; The current module contains claims that fully replace the
; target module claims. This is applied when the module is
; updated or changes in some fashion.
comid.updates = 3
; The current tag contains corrections to a previously
; issued tag. This tag replaces the target tag. The tag-id
; remains unchanged. The tag-version is incremented.
comid.replaces = 4
; The current module contains claims that partially replace
; the target module claims. This is applied when the module
; is updated or changes in some fashion.  The target module
; contains both valid and replaced claims.
comid.patches = 5

; claims-entry
comid.reference-values = 0
comid.endorsements = 1
comid.identity-claims = 2
comid.instance-claims = 3

; identity-claim-map
comid.device-id = 0
comid.key-material = 1

; instance-value-map and $instance-value-choice
comid.instance-element-name = 0
comid.mac-addr = 1
comid.ip-addr = 2
comid.serial-number = 3
comid.ueid = 4
comid.uuid = 5

; corim-meta
signer = 98
deny-id = 99

; validity-entry
not-before = 100
not-after = 101

; unsigned-corim
corim-id = 123 ; TBD
tags = 97
dependent-rims = 122; TBD

; vim: set tw=60 ts=2 et:
