; concise-mid-tag
comid.triples = 5

; triples-map
comid.reference-triples = 0
comid.endorsed-triples = 1
comid.identity-triples = 2
comid.attest-key-triples = 3

; environment-map
comid.class = 0
comid.instance = 1

; class-map
comid.class-id = 0
comid.layer = 1
comid.index = 2
comid.vendor = 3
comid.model = 4

; instance-map
comid.instance-id = 0

; measurement-map
comid.ver = 0
comid.svn = 1
comid.digests = 2
comid.flags = 3
comid.raw-value = 4
comid.raw-value-mask = 5
comid.mac-addr = 6
comid.ip-addr = 7
comid.serial-number = 8
comid.ueid = 9
comid.uuid = 10

; verification-key
corim.key = 0
corim.keychain = 1

; version-map
comid.version = 0
comid.version-scheme = 1

; vim: set tw=60 ts=2 et:
