; concise-mid-tag
comid.language = 0
comid.tag-identity = 1
comid.entities = 2
comid.linked-tags = 3
comid.triples = 4

; tag-identity-map
comid.tag-id = 0
comid.tag-version = 1

; entity-map
comid.entity-name = 0
comid.reg-id = 1
comid.role = 2

; linked-tag-map
comid.linked-tag-id = 0
comid.tag-rel = 1

; triples-map
comid.reference-triples = 0
comid.endorsed-triples = 1
comid.identity-triples = 2
comid.attest-key-triples = 3

; environment-map
comid.class = 0
comid.instance = 1
comid.group = 2

; class-map
comid.class-id = 0
comid.vendor = 1
comid.model = 2
comid.layer = 3
comid.index = 4

; measurement-map
comid.mkey = 0
comid.mval = 1

; measurement-values-map
comid.ver = 0
comid.svn = 1
comid.digests = 2
comid.flags = 3
comid.raw-value = 4
comid.raw-value-mask = 5
comid.mac-addr = 6
comid.ip-addr = 7
comid.serial-number = 8
comid.ueid = 9
comid.uuid = 10

; verification-key-map
comid.key = 0
comid.keychain = 1

; version-map
comid.version = 0
comid.version-scheme = 1

; The current CoMID has additional triples that augment the
; triples of the target CoMID.
comid.supplements = 0

; The current CoMID contains corrections to a previously
; issued CoMID.  This tag replaces the target tag. The tag-id
; remains unchanged. The tag-version is incremented.
comid.replaces = 1

comid.tag-creator = 0
comid.creator = 1
comid.maintainer = 2

; vim: set tw=60 ts=2 et:
