; $rel extensions
$rel /= requires-module
$rel /= runs-on-module

; A software module identified by this tag may require or
; depend on the referenced (firmware) module to be loaded or
; present
requires-module = 12

; A software module identified by this tag runs on a module
; identified by the linked tag(s). The module here
; represents the hardware where this software is executed
runs-on-module = 13

; $role extensions
$role /= module-creator
$role /= module-distributor
$role /= module-licensor
$role /= module-maintainer
$role /= corim-creator
$role /= corim-signer

; module creator
module-creator = 7

; module distributor, entity that furthers marketing, selling or distribution of module 
module-distributor = 8

; module licensor, person or org that holds the right to issue a module license
module-licensor = 9

; module maintainer, person or org making updates to a module. To be used when entity is different than module creator
module-maintainer = 10

; corim creator
corim-creator = 11

; corim signer, person or org responsible for signing the CoRIM
corim-signer = 12

; vim: set tw=60 ts=2 et:
