; corim-map
corim.id = 0
corim.tags = 1
corim.dependent-rims = 2
corim.profile = 3
corim.rim-validity = 4
corim.entities = 5

; corim-locator-map
corim.href = 0
corim.thumbprint = 1

; protected-corim-header-map
corim.alg-id = 1
corim.content-type = 3
corim.issuer-key-id = 4
corim.meta = 8

; validity-map
corim.not-before = 0
corim.not-after = 1

; corim-meta-map
corim.signer = 0
corim.signature-validity = 1

; corim-signer-map
corim.signer-name = 0
corim.signer-uri = 1

; corim-entity-map
corim.entity-name = 0
corim.reg-id = 1
corim.role = 2

; $entity-name-type-choice values
;
; Person or organization responsible for creating the CoRIM
corim.manifest-creator = 1

; vim: set tw=60 ts=2 et:
