; depends on common.cddl for cose-{label,values}

COSE_Key = {
  1 => tstr / int           ; kty
  ? 2 => bstr               ; kid
  ? 3 => tstr / int         ; alg
  ? 4 => [+ (tstr / int) ]  ; key_ops
  ? 5 => bstr               ; Base IV
  * cose-label => cose-values
}

COSE_KeySet = [+COSE_Key]

; vim: set tw=60 ts=2 et:
