signed-corim = #6.18(COSE-Sign1-corim)

protected-signed-corim-header-map = {
  corim.alg-id => int
  corim.content-type => "application/rim+cbor"
  corim.issuer-key-id => bstr
  corim.meta => bstr .cbor corim-meta-map
  * cose-label => cose-values 
}

corim-meta-map = {
  corim.signer => corim-signer-map
  ? corim.signature-validity => validity-map
}

corim-signer-map = {
  corim.signer-name => $entity-name-type-choice
  ? corim.signer-uri => uri
  * $$corim-signer-map-extension
}

validity-map = {
  ? corim.not-before => time
  corim.not-after => time
}

unprotected-signed-corim-header-map = {
  * cose-label => cose-values
}

COSE-Sign1-corim = [
  protected: bstr .cbor protected-signed-corim-header-map
  unprotected: unprotected-signed-corim-header-map
  payload: bstr .cbor unsigned-corim-map
  signature: bstr
]

; vim: set tw=60 ts=2 et:
