signed-corim = #6.18(COSE-Sign1-corim)

cose-label = int / tstr
cose-values = any

protected-signed-corim-header = {
  1 => int,                      ; algorithm identifier
  3 => "application/rim+cbor",   ; content type identifier
  4 => bstr,                     ; key identifier of issuer?
  corim-meta-key => corim-meta   ; corim signature attrs
  * cose-label => cose-values,
}

; scoped to protected-signed-corim-header map
corim-meta-key = 8 

; corim-entity-map is pointing to the details regarding construction and signing of manifest
; tag-metadata tag-issuer these are different things
corim-meta = {
  corim.entity => one-or-more<corim-entity-map>
  ? validity-entry
}

corim-entity-map = {
  corim.entity-name => text,
  ? corim.reg-id => any-uri,
  corim.role => one-or-more<$rim-role>,
  * $$corim-entity-map-extension
}

$rim-role /= corim.creator
$rim-role /= corim.signer

validity-entry = (
  ? not-before => time,
  not-after => time,
)

unprotected-signed-corim-header = {
  * cose-label => cose-values,
}

COSE-Sign1-corim = [
  protected: bstr .cbor protected-signed-corim-header,
  unprotected: unprotected-signed-corim-header,
  payload: bstr .cbor unsigned-corim,
  signature: bstr,
]

; vim: set tw=60 ts=2 et:
