unsigned-corim-map = {
  corim.id => $corim-id-type-choice
  corim.tags => one-or-more<$concise-tag-type-choice>
  ? corim.dependent-rims => one-or-more<corim-locator-map>
  ? corim.profile => one-or-more<profile-type-choice>
  * $$unsigned-corim-map-extension
}

profile-type-choice = uri / tagged-oid-type

corim-locator-map = {
  corim.href => uri
  ? corim.thumbprint => hash-entry
}

; NOTE(henk) does a concise-mid-tag by itself should be
; allowed to be signed the same as a CoSWID tag?
$concise-tag-type-choice /= #6.505(bytes .cbor concise-swid-tag)
$concise-tag-type-choice /= #6.506(bytes .cbor concise-mid-tag)

; vim: set tw=60 ts=2 et:
