corim-revocation = #6.525($corim-revocation-type-choice)

$corim-revocation-type-choice /= #6.526(unsigned-xcorim-map)
$corim-revocation-type-choice /= #6.527(signed-xcorim)

signed-xcorim = #6.18(COSE-Sign1-xcorim)

protected-signed-xcorim-header-map = {
  xcorim.alg-id => int
  xcorim.content-type => "application/xrim+cbor"
  xcorim.issuer-key-id => bstr
  xcorim.meta => xcorim-meta-map
  * cose-label => cose-values
}

xcorim-meta-map = {
  xcorim.signer => xcorim-entity-map
  xcorim.timestamp => time
}

xcorim-entity-map = {
  xcorim.entity-name => $entity-name-type-choice
  xcorim.role => one-or-more<$xcorim-role-type-choice>
  ? xcorim.reg-id => uri
  * $$xcorim-entity-map-extension
}

$xcorim-role-type-choice /= xcorim.deny-list-signer
$xcorim-role-type-choice /= xcorim.deny-list-creator

unprotected-signed-xcorim-header-map = {
  * cose-label => cose-values
}

COSE-Sign1-xcorim = [
  protected: bstr .cbor protected-signed-xcorim-header-map
  unprotected: unprotected-signed-xcorim-header-map
  payload: bstr .cbor unsigned-xcorim-map
  signature: bstr
]

unsigned-xcorim-map = {
  ? xcorim.creator => xcorim-entity-map
  xcorim.deny-list => one-or-more<$corim-id-type-choice>
  * $$unsigned-xcorim-map-extension
}

; vim: set tw=60 ts=2 et:
