xcorim = #6.525($xcorim-type-choice)

$xcorim-type-choice /= #6.526(xcorim-map)
$xcorim-type-choice /= #6.527(signed-xcorim)

signed-xcorim = #6.18(COSE-Sign1-xcorim)

protected-xcorim-header-map = {
  xcorim.alg-id => int
  xcorim.content-type => "application/xrim+cbor"
  xcorim.issuer-key-id => bstr
  xcorim.meta => bstr .cbor xcorim-meta-map
  * cose-label => cose-values
}

xcorim-meta-map = {
  xcorim.signer => xcorim-signer-map
  xcorim.timestamp => time
}

xcorim-signer-map = {
  xcorim.signer-name => $entity-name-type-choice
  ? xcorim.signer-uri => uri
  * $$xcorim-entity-map-extension
}

xcorim-entity-map = {
  xcorim.entity-name => $entity-name-type-choice
  ? xcorim.reg-id => uri
  xcorim.role => $xcorim-role-type-choice
  * $$xcorim-entity-map-extension
}

$xcorim-role-type-choice /= xcorim.deny-list-creator

unprotected-xcorim-header-map = {
  * cose-label => cose-values
}

COSE-Sign1-xcorim = [
  protected: bstr .cbor protected-xcorim-header-map
  unprotected: unprotected-xcorim-header-map
  payload: bstr .cbor xcorim-map
  signature: bstr
]

xcorim-map = {
  ? xcorim.entity => [ + xcorim-entity-map ]
  xcorim.deny-list => [ + $corim-id-type-choice ]
  * $$xcorim-map-extension
}

; vim: set tw=60 ts=2 et:
