; xcorim-map
xcorim.entity = 0
xcorim.deny-list = 1

; xcorim-signer-map
xcorim.signer-name = 0
xcorim.signer-uri = 1

; xcorim-entity-map
xcorim.entity-name = 0
xcorim.role = 1
xcorim.reg-id = 2

; $xcorim-role-type-choice
;
; The person or organization that created the xCoRIM
xcorim.deny-list-creator = 1

; protected-xcorim-header-map
xcorim.alg-id = 1
xcorim.content-type = 3
xcorim.issuer-key-id = 4
xcorim.meta = 9

; xcorim-meta-map
xcorim.signer = 0
xcorim.timestamp = 1

; vim: set tw=60 ts=2 et:
