name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: install cbor-diag and cddl 
        run: gem install --user-install cbor-diag cddl
      - name: set up PATH
        run: echo "$(gem env gempath | cut -d':' -f1)/bin" >> $GITHUB_PATH
      - uses: actions/checkout@v2
      - name: assemble CoRIM cddl from fragments and check the result
        run: make check
