name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: install cddl
        run: gem install --user-install cddl
      - uses: actions/checkout@v2
      - name: assemble CoRIM cddl from fragments and check the result
        run: cddl="$(gem env gempath | cut -d':' -f1)/bin/cddl" make check
